#####################################################
# Peter Waldner, 8.4.2016
# 
# Installation 
# Database Connection To ORACLE under Windows with ODBC
# 
#################################################

# Requirements 
    # ask DB Administrator to create a user account and provide username and passwort for the Oracle-DB
    # ask Windows Administrators for the Administrator Password of your Computer

# Windows
> ODBC Treiber fuer Oracle installieren (falls nicht bereits vorinstalliert) 
    Quelle: Rolf Meile: DB Spacial Client
    <http://webintra.wsl.ch/lfi/doku/htdocs/dab/oraclientrodbc.php>
    
    download
    http://webintra.wsl.ch/lfi/doku/htdocs/dab/ORACLE64.zip
    http://webintra.wsl.ch/lfi/doku/htdocs/dab/ORACLE32.zip
    extract and copy to 
    c:\prog\Oracle64\instantclient_12_1
    c:\prog\Oracle32\instantclient_12_1
    run as administrator
    c:\prog\Oracle64\instantclient_12_1\odbc_install.exe
    c:\prog\Oracle32\instantclient_12_1\odbc_install.exe
   
    control panel > Advanced > advanced system settings > environment variables
    path=...;c:\prog\Oracle64\instantclient_12_1;c:\prog\Oracle32\instantclient_12_1 

  ORA_TNS = 
  ORACLE_HOME = C:\prog\oracle64\instantclient_12_1
  ORACLE_SID = kla01.wsl.ch
  TNS_ADMIN = C:\prog\oracle64\instantclient_12_1\network\admin

  copy das File 'tnsnames.ora' into C:\prog\oracle64\instantclient_12_1\network\admin

Das File 'tnsnames.ora' ist ein Text File mit z.B. folgendem Inhalt
# ----------------
# tnsnames.ora Network Configuration File: /disk01/app/oracle/product/10gR2/network/admin/tnsnames.ora
# Generated by Oracle configuration tools.

EXTPROC_CONNECTION_DATA.WSL.CH =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = IPC)(Key = EXTPROC))
    )
    (CONNECT_DATA =
      (SID = PLSExtProc)
      (PRESENTATION = RO)
    )
  )

INST1_HTTP.WSL.CH =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = klaros.wsl.ch)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = SHARED)
      (SERVICE_NAME = MODOSE)
      (PRESENTATION = http://HRService)
    )
  )

KLA01.WSL.CH =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = klaros)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = kla01.wsl.ch)
    )
  )
  
KLAROS.WSL.CH =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = klaros)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = kla01.wsl.ch)
    )
  )

MAUS.WSL.CH =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = maus)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = bild.wsl.ch)
    )
  )
  
 AMBER.WSL.CH =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = amber)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ambra.wsl.ch)
    )
  )  
  
merkur.wsl.ch =  
    (DESCRIPTION =
           (ADDRESS_LIST =
             (ADDRESS = (PROTOCOL = TCP)(HOST = merkur.wsl.ch)(PORT = 1610))
             (ADDRESS = (PROTOCOL = TCP)(HOST = klaros.wsl.ch)(PORT = 1521))
           )
           (SOURCE_ROUTE = YES)
           (CONNECT_DATA =
            (SID = kla01)
           )
    )
-----------------------------------------------
  
> ODBC Einstellungen 64-bit (R. Meile)
  -------------------------   
    control panel > administrativ tools > SystemDSN
    
    Add: Oracle in instantclient_12_1, Finish
     Data Source Name: klaros
     Description: LWF Oracle DB
     TNS-services Name: kla01.wsl.ch
     User ID: leave blank
    Test Connection

> ODBC Einstellungen 32-bit (P. Jakob, R. Meile)
  -------------------------
    Start > Run > C:\Windows\SysWOW64\odbcad32.exe
    SystemDSN
    Add: Oracle in instantclient_12_1, Finish
     Data Source Name: klaros
     Description: LWF Oracle DB
      TNS-services Name: kla01.wsl.ch
     User ID: leave blank
    Test Connection
   